'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zoller_Storage_Editor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Hotkeys&gt;
        '''	&lt;Item keystring=&quot;Ctrl+O&quot; keystroke=&quot;^O&quot;&gt;mnuOpen_Click&lt;/Item&gt;
        '''	&lt;Item keystring=&quot;Ctrl+S&quot; keystroke=&quot;^S&quot;&gt;mnuSave_Click&lt;/Item&gt;
        '''	&lt;Item keystring=&quot;Alt+W&quot; keystroke=&quot;%W&quot;&gt;mnuEditWidth_Click&lt;/Item&gt;
        '''	&lt;Item keystring=&quot;Alt+D&quot; keystroke=&quot;%D&quot;&gt;mnuEditDepth_Click&lt;/Item&gt;
        '''	&lt;Item keystring=&quot;Alt+H&quot; keystroke=&quot;%H&quot;&gt;mnuEditHeight_Click&lt;/Item&gt;
        '''	&lt;Item keystring=&quot;Alt+X&quot; keystroke=&quot;%X&quot;&gt;mnuEditLocationX_Click&lt;/Item&gt;
        '''	&lt;Item keystring=&quot;Alt+Y&quot; keystroke=&quot;%Y&quot;&gt;mnuEditLocationY_Click [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HotKeyMap() As String
            Get
                Return ResourceManager.GetString("HotKeyMap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F1={F1}
        '''F2={F2}
        '''F3={F3}
        '''F4={F4}
        '''F5={F5}
        '''F6={F6}
        '''F7={F7}
        '''F8={F8}
        '''F9={F9}
        '''F10={F10}
        '''F11={F11}
        '''F12={F12}
        '''Del={DEL}
        '''Ins={INS}
        '''Tab={TAB}
        '''Enter={ENTER}
        '''Esc={ESC}
        '''Home={HOME}
        '''End={END}
        '''Page Up={PGUP}
        '''Page Down={PGDN}
        '''Down Arrow={DOWN}
        '''Up Arrow={UP}
        '''Left Arrow={LEFT}
        '''Right Arrow={RIGHT}
        '''A=A
        '''B=B
        '''C=C
        '''D=D
        '''E=E
        '''F=F
        '''G=G
        '''H=H
        '''I=I
        '''J=J
        '''K=K
        '''L=L
        '''M=M
        '''N=N
        '''O=O
        '''P=P
        '''Q=Q
        '''R=R
        '''S=S
        '''T=T
        '''U=U
        '''V=V
        '''W=W
        '''X=X
        '''Y=Y
        '''Z=Z
        '''0=0
        '''1=1
        '''2=2
        '''3=3
        '''4=4
        '''5=5
        '''6=6
        '''7=7
        '''8=8
        '''9=9.
        '''</summary>
        Friend ReadOnly Property HotKeyValuePair() As String
            Get
                Return ResourceManager.GetString("HotKeyValuePair", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
